/**
 * Synthetic Nora CRM demo data — Düsseldorf / Neuss / Umgebung.
 * All names, addresses and contact details are fictional (@nora-demo.local).
 */

export type CompanySeed = {
  id: number;
  name: string;
  sector: string;
  city: string;
  zipcode: string;
  address: string;
  phone_number: string;
  description: string;
  size: number;
  website?: string;
  createdDaysAgo: number;
};

export type ContactSeed = {
  id: number;
  company_id: number;
  first_name: string;
  last_name: string;
  gender: "male" | "female";
  title: string;
  email?: string;
  phone: string;
  background: string;
  status: "hot" | "warm" | "cold" | "in-contract";
  tags: number[];
};

export type DealSeed = {
  id: number;
  name: string;
  company_id: number;
  contact_ids: number[];
  category: string;
  stage: string;
  description: string;
  /** Amount in euros; 0 = not yet calculated */
  amountEur: number;
  createdDaysAgo: number;
  updatedDaysAgo: number;
  /** Days from today for expected_closing_date (negative = overdue) */
  followUpDaysFromNow: number;
};

export type TaskSeed = {
  id: number;
  contact_id: number;
  type: string;
  text: string;
  dueDaysFromNow: number;
  done?: boolean;
};

export type ContactNoteSeed = {
  contact_id: number;
  text: string;
  daysAgo: number;
  status: string;
};

export type DealNoteSeed = {
  deal_id: number;
  text: string;
  daysAgo: number;
};

/** 25 fiktive Kunden in der Region Düsseldorf / Neuss / Umgebung */
export const DUesseldorf_COMPANY_SEEDS: CompanySeed[] = [
  {
    id: 0,
    name: "Rheinbogen Immobilienservice GmbH",
    sector: "hausverwaltung",
    city: "Düsseldorf",
    zipcode: "40217",
    address: "Bilker Allee 124",
    phone_number: "+49 211 000 41 01",
    description:
      "Hausverwaltung mit mehreren Mehrfamilienhäusern in Bilk und Unterbilk.",
    size: 45,
    website: "https://rheinbogen-demo.local",
    createdDaysAgo: 120,
  },
  {
    id: 1,
    name: "Familie Krüger",
    sector: "privatkunde",
    city: "Neuss",
    zipcode: "41462",
    address: "Further Straße 88",
    phone_number: "+49 2131 000 11 08",
    description: "Privater Eigentümer, wiederkehrende Fensterreparaturen.",
    size: 1,
    createdDaysAgo: 90,
  },
  {
    id: 2,
    name: "Praxis Dr. Lenz & Partner",
    sector: "gewerbekunde",
    city: "Düsseldorf",
    zipcode: "40223",
    address: "Aachener Straße 42",
    phone_number: "+49 211 000 76 30",
    description: "Arztpraxis — Arbeiten nur außerhalb der Sprechzeiten.",
    size: 12,
    website: "https://praxis-lenz-demo.local",
    createdDaysAgo: 100,
  },
  {
    id: 3,
    name: "Wohnen am Stadtwald KG",
    sector: "hausverwaltung",
    city: "Kaarst",
    zipcode: "41564",
    address: "Girmes-Kreuz-Straße 17",
    phone_number: "+49 2131 000 48 22",
    description: "Betreut Wohnanlagen in Kaarst und Büttgen.",
    size: 30,
    createdDaysAgo: 110,
  },
  {
    id: 4,
    name: "Bäckerei Steinofen Neuss",
    sector: "gewerbekunde",
    city: "Neuss",
    zipcode: "41460",
    address: "Oberstraße 51",
    phone_number: "+49 2131 000 30 19",
    description: "Filiale mit Schaufensterfront und Lieferanteneingang.",
    size: 8,
    createdDaysAgo: 80,
  },
  {
    id: 5,
    name: "Autohaus Rheinpark GmbH",
    sector: "bestandskunde",
    city: "Düsseldorf",
    zipcode: "40472",
    address: "Rather Broich 92",
    phone_number: "+49 211 000 88 40",
    description: "Bestandskunde; Showroom-Fenster und Nebengebäude.",
    size: 55,
    website: "https://rheinpark-auto-demo.local",
    createdDaysAgo: 200,
  },
  {
    id: 6,
    name: "Hausgemeinschaft Hafenblick",
    sector: "privatkunde",
    city: "Düsseldorf",
    zipcode: "40221",
    address: "Speditionstraße 23",
    phone_number: "+49 211 000 56 18",
    description: "Eigentümergemeinschaft, Abstimmung über Beirat.",
    size: 1,
    createdDaysAgo: 95,
  },
  {
    id: 7,
    name: "Hotel Rheinperle",
    sector: "gewerbekunde",
    city: "Meerbusch",
    zipcode: "40667",
    address: "Dorfstraße 9",
    phone_number: "+49 2132 000 92 10",
    description: "Hotelbetrieb; Zimmerzugang vorher abstimmen.",
    size: 40,
    createdDaysAgo: 70,
  },
  {
    id: 8,
    name: "Beschläge Nordwest GmbH",
    sector: "lieferant-hersteller",
    city: "Ratingen",
    zipcode: "40878",
    address: "Industrieweg 14",
    phone_number: "+49 2102 000 64 44",
    description: "Demo-Herstellerkontakt für Fensterbeschläge und Ersatzteile.",
    size: 120,
    createdDaysAgo: 300,
  },
  {
    id: 9,
    name: "Kita Sonnenwinkel",
    sector: "sonstiges",
    city: "Neuss",
    zipcode: "41464",
    address: "Weberstraße 31",
    phone_number: "+49 2131 000 71 12",
    description:
      "Sicherheitsrelevante Arbeiten nur nach Absprache mit Leitung.",
    size: 15,
    createdDaysAgo: 60,
  },
  {
    id: 10,
    name: "Malerbetrieb Hoffmann",
    sector: "neukunde",
    city: "Dormagen",
    zipcode: "41539",
    address: "Kölner Straße 183",
    phone_number: "+49 2133 000 19 77",
    description: "Neukunde über Empfehlung; Gewerberäume und Lager.",
    size: 6,
    createdDaysAgo: 14,
  },
  {
    id: 11,
    name: "Objektservice Niederberg",
    sector: "hausverwaltung",
    city: "Erkrath",
    zipcode: "40699",
    address: "Bahnstraße 66",
    phone_number: "+49 211 000 37 29",
    description: "Verwaltet kleinere Wohnobjekte im Kreis Mettmann.",
    size: 20,
    createdDaysAgo: 150,
  },
  {
    id: 12,
    name: "Familie Schneider",
    sector: "privatkunde",
    city: "Ratingen",
    zipcode: "40882",
    address: "Westring 14",
    phone_number: "+49 2102 000 55 01",
    description: "Privatkunde mit Balkontür-Problemen.",
    size: 1,
    createdDaysAgo: 40,
  },
  {
    id: 13,
    name: "Schneider Hausverwaltung",
    sector: "hausverwaltung",
    city: "Düsseldorf",
    zipcode: "40211",
    address: "Friedrichstraße 88",
    phone_number: "+49 211 000 55 02",
    description:
      "Hausverwaltung — ähnlicher Name zu Familie Schneider (Dubletten-Test).",
    size: 25,
    createdDaysAgo: 130,
  },
  {
    id: 14,
    name: "Immobilien Weber NRW",
    sector: "bestandskunde",
    city: "Meerbusch",
    zipcode: "40670",
    address: "Kapellenstraße 5",
    phone_number: "+49 2132 000 33 40",
    description: "Immobilienservice mit mehreren Bestandsobjekten.",
    size: 18,
    createdDaysAgo: 180,
  },
  {
    id: 15,
    name: "Café am Rhein",
    sector: "gewerbekunde",
    city: "Neuss",
    zipcode: "41460",
    address: "Hamtorstraße 12",
    phone_number: "+49 2131 000 22 15",
    description: "Gastronomie mit großer Fensterfront zur Promenade.",
    size: 5,
    createdDaysAgo: 55,
  },
  {
    id: 16,
    name: "Seniorenresidenz Parkblick",
    sector: "sonstiges",
    city: "Erkrath",
    zipcode: "40699",
    address: "Parkstraße 44",
    phone_number: "+49 2104 000 81 20",
    description: "Pflegeeinrichtung mit Hausmeistervertrag.",
    size: 80,
    createdDaysAgo: 220,
  },
  {
    id: 17,
    name: "Bürocenter Medienhafen",
    sector: "gewerbekunde",
    city: "Düsseldorf",
    zipcode: "40219",
    address: "Speditionsstraße 15",
    phone_number: "+49 211 000 62 30",
    description: "Bürokomplex mit regelmäßiger Fensterwartung.",
    size: 100,
    createdDaysAgo: 160,
  },
  {
    id: 18,
    name: "Grundschule Am Wasserturm",
    sector: "sonstiges",
    city: "Dormagen",
    zipcode: "41541",
    address: "Wasserturmweg 3",
    phone_number: "+49 2133 000 45 10",
    description: "Öffentliche Einrichtung; Termine nur in Ferienzeiten.",
    size: 35,
    createdDaysAgo: 250,
  },
  {
    id: 19,
    name: "Familie Becker",
    sector: "privatkunde",
    city: "Neuss",
    zipcode: "41462",
    address: "Jülicher Landstraße 201",
    phone_number: "+49 2131 000 88 01",
    description:
      "Privatkunde — ähnlicher Name zu Becker Immobilien (Dubletten-Test).",
    size: 1,
    createdDaysAgo: 35,
  },
  {
    id: 20,
    name: "Becker Immobilien GmbH",
    sector: "gewerbekunde",
    city: "Düsseldorf",
    zipcode: "40212",
    address: "Königsallee 78",
    phone_number: "+49 211 000 88 02",
    description: "Immobilienservice — Dubletten-Test zu Familie Becker.",
    size: 15,
    createdDaysAgo: 140,
  },
  {
    id: 21,
    name: "WEG Königsallee 12",
    sector: "privatkunde",
    city: "Düsseldorf",
    zipcode: "40212",
    address: "Königsallee 12",
    phone_number: "+49 211 000 12 00",
    description:
      "Wohnungseigentümergemeinschaft — bewusst ohne Ansprechpartner (UI-Test).",
    size: 1,
    createdDaysAgo: 75,
  },
  {
    id: 22,
    name: "Tischlerei Nordrhein",
    sector: "lieferant-hersteller",
    city: "Kaarst",
    zipcode: "41564",
    address: "Holzweg 7",
    phone_number: "+49 2131 000 70 55",
    description: "Lieferant für Holzfenster und Rahmen.",
    size: 30,
    createdDaysAgo: 280,
  },
  {
    id: 23,
    name: "Fitnessstudio Vitalis",
    sector: "gewerbekunde",
    city: "Kaarst",
    zipcode: "41564",
    address: "Sportplatzstraße 2",
    phone_number: "+49 2131 000 91 33",
    description: "Gewerbekunde mit großen Schaufensterfronten.",
    size: 12,
    createdDaysAgo: 45,
  },
  {
    id: 24,
    name: "Parkhaus City Düsseldorf",
    sector: "gewerbekunde",
    city: "Düsseldorf",
    zipcode: "40213",
    address: "Kasernenstraße 6",
    phone_number: "+49 211 000 99 10",
    description: "Parkhaus mit Kellerfenstern und Lüftungsgittern.",
    size: 20,
    createdDaysAgo: 65,
  },
];

/** 30 fiktive Ansprechpartner */
export const DUesseldorf_CONTACT_SEEDS: ContactSeed[] = [
  {
    id: 0,
    company_id: 0,
    first_name: "Katharina",
    last_name: "Becker",
    gender: "female",
    title: "Objektbetreuung",
    email: "k.becker@rheinbogen-demo.local",
    phone: "+49 211 000 41 02",
    background: "Zuständig für Bilk und Unterbilk.",
    status: "hot",
    tags: [0, 2],
  },
  {
    id: 1,
    company_id: 0,
    first_name: "Paul",
    last_name: "Mertens",
    gender: "male",
    title: "Mieter",
    email: "p.mertens@nora-demo.local",
    phone: "+49 211 000 41 09",
    background: "Mieter im Objekt Bilk, meldet klemmendes Fenster.",
    status: "warm",
    tags: [0],
  },
  {
    id: 2,
    company_id: 0,
    first_name: "Leonie",
    last_name: "Brandt",
    gender: "female",
    title: "Assistenz Verwaltung",
    email: "l.brandt@rheinbogen-demo.local",
    phone: "+49 211 000 41 03",
    background: "Bittet um Fotodokumentation nach Abschluss.",
    status: "warm",
    tags: [2],
  },
  {
    id: 3,
    company_id: 1,
    first_name: "Jens",
    last_name: "Krüger",
    gender: "male",
    title: "Eigentümer",
    email: "jens.krueger@nora-demo.local",
    phone: "+49 2131 000 11 09",
    background: "Defekter Fenstergriff im Wohnzimmer. Erreichbar ab 17 Uhr.",
    status: "hot",
    tags: [0],
  },
  {
    id: 4,
    company_id: 2,
    first_name: "Mara",
    last_name: "Lenz",
    gender: "female",
    title: "Ärztin / Inhaberin",
    email: "m.lenz@praxis-lenz-demo.local",
    phone: "+49 211 000 76 31",
    background: "Entscheidet über Reparaturfreigaben in der Praxis.",
    status: "warm",
    tags: [0],
  },
  {
    id: 5,
    company_id: 2,
    first_name: "Nadine",
    last_name: "Schulz",
    gender: "female",
    title: "Praxismanagerin",
    email: "n.schulz@praxis-lenz-demo.local",
    phone: "+49 211 000 76 32",
    background: "Koordiniert Termine außerhalb der Sprechzeiten.",
    status: "hot",
    tags: [0],
  },
  {
    id: 6,
    company_id: 3,
    first_name: "Thomas",
    last_name: "Wegner",
    gender: "male",
    title: "Technischer Verwalter",
    email: "t.wegner@stadtwald-demo.local",
    phone: "+49 2131 000 48 23",
    background: "Benötigt Angebote mit Positionsbeschreibung je Objekt.",
    status: "hot",
    tags: [2, 0],
  },
  {
    id: 7,
    company_id: 3,
    first_name: "Svenja",
    last_name: "Roth",
    gender: "female",
    title: "Buchhaltung",
    email: "s.roth@stadtwald-demo.local",
    phone: "+49 2131 000 48 24",
    background: "Prüft Rechnungsadressen vor Freigabe.",
    status: "warm",
    tags: [2],
  },
  {
    id: 8,
    company_id: 4,
    first_name: "Selin",
    last_name: "Arslan",
    gender: "female",
    title: "Filialleitung",
    email: "s.arslan@steinofen-demo.local",
    phone: "+49 2131 000 30 20",
    background: "Schaufenstergriff klemmt; Reparatur vor Ladenöffnung.",
    status: "warm",
    tags: [0],
  },
  {
    id: 9,
    company_id: 5,
    first_name: "Markus",
    last_name: "Seidel",
    gender: "male",
    title: "Serviceleiter",
    email: "m.seidel@rheinpark-auto-demo.local",
    phone: "+49 211 000 88 41",
    background: "Kennt Objektzugänge und Werkstattbereich.",
    status: "in-contract",
    tags: [4, 0],
  },
  {
    id: 10,
    company_id: 5,
    first_name: "Anna",
    last_name: "Köhler",
    gender: "female",
    title: "Empfang",
    email: "a.koehler@rheinpark-auto-demo.local",
    phone: "+49 211 000 88 42",
    background: "Nimmt Termine für das Autohaus entgegen.",
    status: "warm",
    tags: [4],
  },
  {
    id: 11,
    company_id: 6,
    first_name: "Claudia",
    last_name: "Reuter",
    gender: "female",
    title: "Beirätin",
    email: "c.reuter@nora-demo.local",
    phone: "+49 211 000 56 19",
    background: "Stimmt Termine für die Hausgemeinschaft ab.",
    status: "warm",
    tags: [1],
  },
  {
    id: 12,
    company_id: 6,
    first_name: "Moritz",
    last_name: "Hansen",
    gender: "male",
    title: "Hausmeister",
    phone: "+49 211 000 56 20",
    background:
      "Kennt Schlüssel und Technikraum — bewusst ohne E-Mail (UI-Test).",
    status: "hot",
    tags: [2],
  },
  {
    id: 13,
    company_id: 7,
    first_name: "Okan",
    last_name: "Demir",
    gender: "male",
    title: "Haustechnik",
    email: "o.demir@rheinperle-demo.local",
    phone: "+49 2132 000 92 11",
    background: "Begleitet Arbeiten vor Ort in den Zimmern.",
    status: "hot",
    tags: [0],
  },
  {
    id: 14,
    company_id: 8,
    first_name: "Petra",
    last_name: "Klein",
    gender: "female",
    title: "Ersatzteilservice",
    email: "p.klein@beschlaege-nw-demo.local",
    phone: "+49 2102 000 64 45",
    background: "Demo-Herstellerkontakt. Gibt Lieferzeiten durch.",
    status: "warm",
    tags: [],
  },
  {
    id: 15,
    company_id: 9,
    first_name: "Anne",
    last_name: "Vogel",
    gender: "female",
    title: "Kita-Leitung",
    email: "a.vogel@sonnenwinkel-demo.local",
    phone: "+49 2131 000 71 13",
    background: "Sicherheitsrelevante Mängel priorisieren.",
    status: "warm",
    tags: [2],
  },
  {
    id: 16,
    company_id: 10,
    first_name: "Ralf",
    last_name: "Hoffmann",
    gender: "male",
    title: "Inhaber",
    email: "ralf.hoffmann@maler-hoffmann-demo.local",
    phone: "+49 2133 000 19 78",
    background: "Neukunde über Empfehlung.",
    status: "cold",
    tags: [],
  },
  {
    id: 17,
    company_id: 11,
    first_name: "Bettina",
    last_name: "Krause",
    gender: "female",
    title: "Disposition",
    email: "b.krause@niederberg-demo.local",
    phone: "+49 211 000 37 30",
    background: "Sammelt Mängelmeldungen für mehrere Objekte.",
    status: "warm",
    tags: [2],
  },
  {
    id: 18,
    company_id: 12,
    first_name: "Sabine",
    last_name: "Schneider",
    gender: "female",
    title: "Eigentümerin",
    email: "sabine.schneider@nora-demo.local",
    phone: "+49 2102 000 55 01",
    background: "Balkontür schließt nicht richtig.",
    status: "hot",
    tags: [0],
  },
  {
    id: 19,
    company_id: 13,
    first_name: "Frank",
    last_name: "Schneider",
    gender: "male",
    title: "Verwalter",
    email: "f.schneider@schneider-hv-demo.local",
    phone: "+49 211 000 55 03",
    background: "Hausverwaltung — ähnlicher Name (Dubletten-Test).",
    status: "warm",
    tags: [2],
  },
  {
    id: 20,
    company_id: 14,
    first_name: "Helmut",
    last_name: "Weber",
    gender: "male",
    title: "Geschäftsführer",
    email: "h.weber@immobilien-weber-demo.local",
    phone: "+49 2132 000 33 41",
    background: "Bestandskunde mit mehreren Objekten.",
    status: "in-contract",
    tags: [4],
  },
  {
    id: 21,
    company_id: 15,
    first_name: "Lisa",
    last_name: "Grimm",
    gender: "female",
    title: "Inhaberin",
    email: "l.grimm@cafe-rhein-demo.local",
    phone: "+49 2131 000 22 16",
    background: "Café mit defekter Fensterfront.",
    status: "warm",
    tags: [0],
  },
  {
    id: 22,
    company_id: 16,
    first_name: "Gertrud",
    last_name: "Sommer",
    gender: "female",
    title: "Einrichtungsleitung",
    email: "g.sommer@parkblick-demo.local",
    phone: "+49 2104 000 81 21",
    background: "Hausmeistervertrag für Seniorenresidenz.",
    status: "in-contract",
    tags: [2],
  },
  {
    id: 23,
    company_id: 17,
    first_name: "Daniel",
    last_name: "Fuchs",
    gender: "male",
    title: "Facility Manager",
    email: "d.fuchs@buero-mh-demo.local",
    phone: "+49 211 000 62 31",
    background: "Koordiniert Fensterwartung im Bürocenter.",
    status: "warm",
    tags: [0, 4],
  },
  {
    id: 24,
    company_id: 18,
    first_name: "Stefan",
    last_name: "Bauer",
    gender: "male",
    title: "Hausmeister",
    email: "s.bauer@wasserturm-demo.local",
    phone: "+49 2133 000 45 11",
    background: "Schulhausmeister, erreichbar in Ferien.",
    status: "warm",
    tags: [2],
  },
  {
    id: 25,
    company_id: 19,
    first_name: "Sabine",
    last_name: "Becker",
    gender: "female",
    title: "Eigentümerin",
    email: "sabine.becker@nora-demo.local",
    phone: "+49 2131 000 88 01",
    background: "Kellerfenster undicht — Dubletten-Test zu Becker Immobilien.",
    status: "hot",
    tags: [0],
  },
  {
    id: 26,
    company_id: 20,
    first_name: "Sabine",
    last_name: "Becker",
    gender: "female",
    title: "Geschäftsführerin",
    email: "sabine.becker@nora-demo.local",
    phone: "+49 2131 000 88 01",
    background:
      "Gleiche E-Mail/Telefon wie Familie Becker — Dubletten-Test Schnellerfassung.",
    status: "warm",
    tags: [4],
  },
  {
    id: 27,
    company_id: 22,
    first_name: "Karl",
    last_name: "Nordmann",
    gender: "male",
    title: "Vertrieb",
    email: "k.nordmann@tischlerei-nr-demo.local",
    phone: "+49 2131 000 70 56",
    background: "Lieferant für Holzfenster.",
    status: "warm",
    tags: [],
  },
  {
    id: 28,
    company_id: 23,
    first_name: "Tim",
    last_name: "Richter",
    gender: "male",
    title: "Betriebsleiter",
    email: "t.richter@vitalis-demo.local",
    phone: "+49 2131 000 91 34",
    background: "Fitnessstudio mit undichten Schaufensterfronten.",
    status: "warm",
    tags: [0],
  },
  {
    id: 29,
    company_id: 24,
    first_name: "Eva",
    last_name: "Scholz",
    gender: "female",
    title: "Technik",
    email: "e.scholz@parkhaus-demo.local",
    phone: "+49 211 000 99 11",
    background: "Kellerfenster im Parkhaus prüfen.",
    status: "hot",
    tags: [0],
  },
];

/** 20 fiktive Vorgänge — alle Nora-Status abgedeckt */
export const DUesseldorf_DEAL_SEEDS: DealSeed[] = [
  {
    id: 0,
    name: "Fenstergriff Wohnzimmer defekt",
    company_id: 1,
    contact_ids: [3],
    category: "fensterservice",
    stage: "neue-anfrage",
    description:
      "Fenstergriff im Wohnzimmer dreht durch. Kunde bittet um Rückruf und Besichtigung.",
    amountEur: 650,
    createdDaysAgo: 3,
    updatedDaysAgo: 1,
    followUpDaysFromNow: 7,
  },
  {
    id: 1,
    name: "Haustür Mehrfamilienhaus schließt nicht richtig",
    company_id: 0,
    contact_ids: [0],
    category: "reparatur",
    stage: "kontaktiert",
    description:
      "Haustür im MFH Bilk fällt nicht zuverlässig ins Schloss. Mieter melden Zugluft.",
    amountEur: 1850,
    createdDaysAgo: 12,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 5,
  },
  {
    id: 2,
    name: "Balkontür schließt nicht richtig",
    company_id: 12,
    contact_ids: [18],
    category: "fensterservice",
    stage: "termin-vereinbart",
    description:
      "Balkontür in Ratingen schließt nicht. Besichtigung am Freitag vereinbart.",
    amountEur: 1450,
    createdDaysAgo: 8,
    updatedDaysAgo: 1,
    followUpDaysFromNow: 3,
  },
  {
    id: 3,
    name: "Aufmaß für Fenstertausch",
    company_id: 3,
    contact_ids: [6],
    category: "fensterservice",
    stage: "aufmass-geplant",
    description:
      "Altes Kellerfenster in Kaarst soll ersetzt werden. Aufmaß und Fotos erforderlich.",
    amountEur: 8000,
    createdDaysAgo: 18,
    updatedDaysAgo: 3,
    followUpDaysFromNow: 10,
  },
  {
    id: 4,
    name: "Fensterbeschläge Showroom warten",
    company_id: 5,
    contact_ids: [9],
    category: "wartung",
    stage: "aufmass-erledigt",
    description:
      "Jährliche Wartung der Showroom-Fenster im Autohaus Rheinpark.",
    amountEur: 2400,
    createdDaysAgo: 30,
    updatedDaysAgo: 5,
    followUpDaysFromNow: 14,
  },
  {
    id: 5,
    name: "Kellerfenster undicht",
    company_id: 19,
    contact_ids: [25],
    category: "fensterservice",
    stage: "in-kalkulation",
    description:
      "Kellerfenster in Neuss undicht. Kalkulation für Austausch läuft.",
    amountEur: 1650,
    createdDaysAgo: 22,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 8,
  },
  {
    id: 6,
    name: "Ersatzteil Fensterbeschlag anfragen",
    company_id: 8,
    contact_ids: [14],
    category: "fensterservice",
    stage: "wartet-auf-hersteller",
    description:
      "Beschlagtyp laut Foto unklar. Hersteller soll Verfügbarkeit prüfen — ohne Auftragswert.",
    amountEur: 0,
    createdDaysAgo: 15,
    updatedDaysAgo: 4,
    followUpDaysFromNow: 12,
  },
  {
    id: 7,
    name: "Angebot Fensterbeschläge nachfassen",
    company_id: 14,
    contact_ids: [20],
    category: "fensterservice",
    stage: "angebot-gesendet",
    description:
      "Angebot für Fensterbeschläge an Immobilien Weber gesendet. Nachfassung offen.",
    amountEur: 3600,
    createdDaysAgo: 20,
    updatedDaysAgo: 3,
    followUpDaysFromNow: 2,
  },
  {
    id: 8,
    name: "Hotelzimmer-Fenster — Angebot nachfassen",
    company_id: 7,
    contact_ids: [13],
    category: "fensterservice",
    stage: "nachfassen",
    description:
      "Angebot telefonisch besprochen. Rückmeldung steht aus — Nachfassdatum überfällig.",
    amountEur: 9300,
    createdDaysAgo: 25,
    updatedDaysAgo: 1,
    followUpDaysFromNow: -3,
  },
  {
    id: 9,
    name: "Kita-Türschließer prüfen",
    company_id: 9,
    contact_ids: [15],
    category: "hausmeisterdienst",
    stage: "angenommen",
    description: "Türschließer am Nebeneingang prüfen und einstellen.",
    amountEur: 450,
    createdDaysAgo: 10,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 5,
  },
  {
    id: 10,
    name: "Lagerfenster Malerbetrieb ersetzen",
    company_id: 10,
    contact_ids: [16],
    category: "fensterservice",
    stage: "abgelehnt",
    description: "Angebot wegen Budget verschoben.",
    amountEur: 5900,
    createdDaysAgo: 14,
    updatedDaysAgo: 5,
    followUpDaysFromNow: -5,
  },
  {
    id: 11,
    name: "Treppenhausfenster Objekt Erkrath",
    company_id: 11,
    contact_ids: [17],
    category: "fensterservice",
    stage: "abgeschlossen",
    description:
      "Treppenhausfenster eingestellt, Griff befestigt, Fotodokumentation erledigt.",
    amountEur: 2100,
    createdDaysAgo: 60,
    updatedDaysAgo: 20,
    followUpDaysFromNow: -30,
  },
  {
    id: 12,
    name: "Klemmendes Schlafzimmerfenster im Objekt Bilk",
    company_id: 0,
    contact_ids: [1],
    category: "fensterservice",
    stage: "neue-anfrage",
    description:
      "Mieter meldet klemmendes Fenster. Verwaltung muss Freigabe geben.",
    amountEur: 890,
    createdDaysAgo: 2,
    updatedDaysAgo: 1,
    followUpDaysFromNow: 0,
  },
  {
    id: 13,
    name: "Treppenhausbeleuchtung prüfen",
    company_id: 16,
    contact_ids: [22],
    category: "hausmeisterdienst",
    stage: "kontaktiert",
    description:
      "Treppenhausbeleuchtung in Seniorenresidenz prüfen — kein Fensterservice, keine Checkliste.",
    amountEur: 680,
    createdDaysAgo: 7,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 4,
  },
  {
    id: 14,
    name: "Wohnungsübergabe vorbereiten",
    company_id: 14,
    contact_ids: [20],
    category: "hausmeisterdienst",
    stage: "termin-vereinbart",
    description: "Kleinreparaturen und Fensterkontrolle vor Wohnungsübergabe.",
    amountEur: 1250,
    createdDaysAgo: 11,
    updatedDaysAgo: 1,
    followUpDaysFromNow: 6,
  },
  {
    id: 15,
    name: "Hausmeisterkontrolle Objekt Lager",
    company_id: 10,
    contact_ids: [16],
    category: "hausmeisterdienst",
    stage: "aufmass-geplant",
    description: "Monatliche Sichtkontrolle im Lager Dormagen.",
    amountEur: 2400,
    createdDaysAgo: 9,
    updatedDaysAgo: 3,
    followUpDaysFromNow: 9,
  },
  {
    id: 16,
    name: "Angebot für neue Haustür",
    company_id: 2,
    contact_ids: [5],
    category: "fensterservice",
    stage: "in-kalkulation",
    description:
      "Neue Haustür für Praxis — Fensterservice mit späterer Produktionsfreigabe.",
    amountEur: 14200,
    createdDaysAgo: 16,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 11,
  },
  {
    id: 17,
    name: "Montage terminieren",
    company_id: 1,
    contact_ids: [3],
    category: "fensterservice",
    stage: "angenommen",
    description:
      "Fenstergriff-Reparatur angenommen — Montagetermin koordinieren.",
    amountEur: 650,
    createdDaysAgo: 6,
    updatedDaysAgo: 1,
    followUpDaysFromNow: 3,
  },
  {
    id: 18,
    name: "Schaufenstergriff klemmt",
    company_id: 4,
    contact_ids: [8],
    category: "reparatur",
    stage: "angebot-gesendet",
    description:
      "Schaufenstergriff klemmt beim Abschließen. Angebot versendet.",
    amountEur: 750,
    createdDaysAgo: 13,
    updatedDaysAgo: 2,
    followUpDaysFromNow: 1,
  },
  {
    id: 19,
    name: "Balkontür Hafenblick zieht",
    company_id: 6,
    contact_ids: [11],
    category: "fensterservice",
    stage: "aufmass-erledigt",
    description:
      "Balkontür in Eigentumswohnung zieht. Dichtungen und Beschlag prüfen.",
    amountEur: 1850,
    createdDaysAgo: 28,
    updatedDaysAgo: 4,
    followUpDaysFromNow: 7,
  },
];

/** 20 fiktive Aufgaben */
export const DUesseldorf_TASK_SEEDS: TaskSeed[] = [
  {
    id: 0,
    contact_id: 3,
    type: "rueckruf",
    text: "Rückruf bei Herrn Krüger wegen Fenstergriff",
    dueDaysFromNow: -1,
  },
  {
    id: 1,
    contact_id: 0,
    type: "besichtigung",
    text: "Besichtigung MFH Bilk – Haustür prüfen",
    dueDaysFromNow: 2,
  },
  {
    id: 2,
    contact_id: 5,
    type: "termin-vereinbaren",
    text: "Termin nach Sprechzeit bestätigen",
    dueDaysFromNow: 3,
  },
  {
    id: 3,
    contact_id: 6,
    type: "aufmass",
    text: "Kellerfenster Kaarst aufmessen und Fotos machen",
    dueDaysFromNow: 4,
  },
  {
    id: 4,
    contact_id: 8,
    type: "angebot-nachfassen",
    text: "Angebot Schaufenstergriff nachfassen",
    dueDaysFromNow: 1,
  },
  {
    id: 5,
    contact_id: 9,
    type: "dokumentation",
    text: "Wartung Showroom-Fenster dokumentieren",
    dueDaysFromNow: 6,
  },
  {
    id: 6,
    contact_id: 11,
    type: "angebot-erstellen",
    text: "Kalkulation Balkontür Hafenblick vorbereiten",
    dueDaysFromNow: 5,
  },
  {
    id: 7,
    contact_id: 14,
    type: "herstelleranfrage",
    text: "Beschlagtyp und Lieferzeit beim Hersteller anfragen",
    dueDaysFromNow: 0,
  },
  {
    id: 8,
    contact_id: 13,
    type: "angebot-nachfassen",
    text: "Hotel Rheinperle – Rückmeldung zur Reparatur einholen",
    dueDaysFromNow: -2,
  },
  {
    id: 9,
    contact_id: 15,
    type: "termin-vereinbaren",
    text: "Kita-Türschließer Termin nach 15 Uhr abstimmen",
    dueDaysFromNow: 2,
  },
  {
    id: 10,
    contact_id: 1,
    type: "rueckruf",
    text: "Mieter Mertens wegen Zeitfenster kontaktieren",
    dueDaysFromNow: 0,
  },
  {
    id: 11,
    contact_id: 16,
    type: "besichtigung",
    text: "Lager Dormagen ansehen und Leistungsumfang klären",
    dueDaysFromNow: 7,
  },
  {
    id: 12,
    contact_id: 18,
    type: "besichtigung",
    text: "Balkontür Ratingen — Besichtigung vorbereiten",
    dueDaysFromNow: 1,
  },
  {
    id: 13,
    contact_id: 20,
    type: "angebot-nachfassen",
    text: "Angebot Fensterbeschläge bei Herrn Weber nachfassen",
    dueDaysFromNow: 2,
  },
  {
    id: 14,
    contact_id: 22,
    type: "besichtigung",
    text: "Treppenhausbeleuchtung Seniorenresidenz prüfen",
    dueDaysFromNow: 3,
  },
  {
    id: 15,
    contact_id: 25,
    type: "angebot-erstellen",
    text: "Angebot Kellerfenster Familie Becker erstellen",
    dueDaysFromNow: 4,
  },
  {
    id: 16,
    contact_id: 23,
    type: "termin-vereinbaren",
    text: "Fensterwartung Bürocenter abstimmen",
    dueDaysFromNow: 5,
  },
  {
    id: 17,
    contact_id: 28,
    type: "besichtigung",
    text: "Schaufenster Fitnessstudio Vitalis begutachten",
    dueDaysFromNow: 6,
  },
  {
    id: 18,
    contact_id: 29,
    type: "aufmass",
    text: "Kellerfenster Parkhaus aufmessen",
    dueDaysFromNow: 8,
  },
  {
    id: 19,
    contact_id: 0,
    type: "rueckruf",
    text: "Rückfrage Verwaltung Rheinbogen zu Mieterfreigabe",
    dueDaysFromNow: 3,
    done: true,
  },
];

export const DUesseldorf_CONTACT_NOTE_SEEDS: ContactNoteSeed[] = [
  {
    contact_id: 3,
    text: "Herr Krüger möchte nach Möglichkeit einen Termin am frühen Abend.",
    daysAgo: 1,
    status: "hot",
  },
  {
    contact_id: 0,
    text: "Fotos der Haustür liegen vor. Schließblech wirkt ausgeschlagen.",
    daysAgo: 2,
    status: "hot",
  },
  {
    contact_id: 20,
    text: "Angebot für Fensterbeschläge versendet. Rückmeldung nächste Woche.",
    daysAgo: 3,
    status: "in-contract",
  },
  {
    contact_id: 9,
    text: "Wartungstermin Autohaus für nächsten Monat in Abstimmung.",
    daysAgo: 5,
    status: "warm",
  },
  {
    contact_id: 6,
    text: "Aufmaß-Termin für Kellerfenster am Donnerstag 14:00 bestätigt.",
    daysAgo: 2,
    status: "warm",
  },
  {
    contact_id: 13,
    text: "Hotelleitung meldet sich bis Freitag zum Angebot.",
    daysAgo: 1,
    status: "hot",
  },
  {
    contact_id: 16,
    text: "Herr Hoffmann vergleicht Angebot mit anderem Anbieter.",
    daysAgo: 7,
    status: "cold",
  },
  {
    contact_id: 17,
    text: "Objektübergabe Erkrath dokumentiert und abgeschlossen.",
    daysAgo: 20,
    status: "in-contract",
  },
  {
    contact_id: 12,
    text: "Hausmeister Hansen nur telefonisch erreichbar — keine E-Mail.",
    daysAgo: 4,
    status: "hot",
  },
  {
    contact_id: 25,
    text: "Frau Becker meldet Feuchtigkeit am Kellerfensterrahmen.",
    daysAgo: 2,
    status: "hot",
  },
];

export const DUesseldorf_DEAL_NOTE_SEEDS: DealNoteSeed[] = [
  {
    deal_id: 1,
    text: "Fotos der Haustür liegen vor. Schließblech wirkt ausgeschlagen.",
    daysAgo: 2,
  },
  {
    deal_id: 8,
    text: "Nachfass-Telefonat mit Herrn Demir vereinbart — Termin überfällig.",
    daysAgo: 1,
  },
  {
    deal_id: 6,
    text: "Herstelleranfrage gesendet. Artikelnummer und Foto liegen vor.",
    daysAgo: 4,
  },
  {
    deal_id: 7,
    text: "Angebot per E-Mail an Herrn Weber gesendet. Gültigkeit 14 Tage.",
    daysAgo: 3,
  },
  {
    deal_id: 16,
    text: "Aufmaß Haustür Praxis erledigt. Kalkulation läuft.",
    daysAgo: 2,
  },
  {
    deal_id: 12,
    text: "Mieterfreigabe durch Verwaltung noch ausstehend.",
    daysAgo: 1,
  },
];
