--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    customer_number text not null
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    case_number text not null
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    role text not null default 'viewer',
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

alter table public.sales
    add constraint sales_role_check check (role in ('admin', 'office', 'viewer'));

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

create table public.number_counters (
    counter_key text not null,
    year smallint not null default 0,
    last_value bigint not null default 0,
    primary key (counter_key, year)
);

revoke all on table public.number_counters from anon;
revoke all on table public.number_counters from authenticated;
revoke all on table public.number_counters from public;

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

alter table only public.companies
    add constraint companies_customer_number_key unique (customer_number);

alter table only public.deals
    add constraint deals_case_number_key unique (case_number);

--
-- Checklists, text snippets, audit (v0.3d2) — see 10-checklists-snippets-audit.md
--

create table public.checklist_templates (
    id uuid primary key default gen_random_uuid(),
    code text not null,
    name text not null,
    service_area_code text not null,
    description text,
    is_active boolean not null default true,
    version integer not null default 1,
    created_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint checklist_templates_code_key unique (code),
    constraint checklist_templates_service_area_code_check
        check (service_area_code in ('FENS', 'HAUS', 'IMMO')),
    constraint checklist_templates_version_check check (version >= 1)
);

create table public.checklist_template_items (
    id uuid primary key default gen_random_uuid(),
    template_id uuid not null references public.checklist_templates (id) on delete restrict,
    label text not null,
    description text,
    is_required boolean not null default false,
    sort_index integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint checklist_template_items_sort_index_check check (sort_index >= 0)
);

create table public.checklist_runs (
    id uuid primary key default gen_random_uuid(),
    template_id uuid not null references public.checklist_templates (id) on delete restrict,
    deal_id bigint not null references public.deals (id) on delete restrict,
    company_id bigint references public.companies (id) on delete restrict,
    contact_id bigint references public.contacts (id) on delete set null,
    service_area_code text not null,
    status text not null default 'open',
    started_by uuid,
    completed_by uuid,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint checklist_runs_service_area_code_check
        check (service_area_code in ('FENS', 'HAUS', 'IMMO')),
    constraint checklist_runs_status_check
        check (status in ('open', 'completed', 'cancelled'))
);

create unique index uq_checklist_runs_one_open_per_deal_template
    on public.checklist_runs (deal_id, template_id)
    where status = 'open';

create table public.checklist_run_items (
    id uuid primary key default gen_random_uuid(),
    checklist_run_id uuid not null references public.checklist_runs (id) on delete restrict,
    template_item_id uuid references public.checklist_template_items (id) on delete set null,
    label_snapshot text not null,
    is_required boolean not null default false,
    is_checked boolean not null default false,
    checked_by uuid,
    checked_at timestamptz,
    note text,
    sort_index integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint checklist_run_items_sort_index_check check (sort_index >= 0)
);

create table public.saved_text_snippets (
    id uuid primary key default gen_random_uuid(),
    service_area_code text not null,
    kind text not null,
    text text not null,
    shortcut text,
    is_active boolean not null default true,
    created_by uuid,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    usage_count integer not null default 0,
    constraint saved_text_snippets_service_area_code_check
        check (service_area_code in ('FENS', 'HAUS', 'IMMO')),
    constraint saved_text_snippets_kind_check
        check (kind in ('checklist_item', 'task_text', 'note_text', 'issue_text')),
    constraint saved_text_snippets_usage_count_check check (usage_count >= 0)
);

create table public.audit_events (
    id uuid primary key default gen_random_uuid(),
    actor_id uuid,
    event_type text not null,
    entity_type text not null,
    entity_id uuid not null,
    company_id bigint,
    contact_id bigint,
    deal_id bigint,
    checklist_run_id uuid,
    checklist_run_item_id uuid,
    task_id bigint,
    note_id bigint,
    old_data jsonb,
    new_data jsonb,
    metadata jsonb,
    actor_sales_id bigint,
    actor_name_snapshot text,
    actor_role_snapshot text,
    source text not null default 'user',
    retention_class text not null default 'crm_change',
    request_id text,
    created_at timestamptz not null default now()
);

create index checklist_templates_service_area_active_idx
    on public.checklist_templates (service_area_code, is_active);

create index checklist_template_items_template_sort_idx
    on public.checklist_template_items (template_id, sort_index);

create index checklist_runs_deal_status_idx on public.checklist_runs (deal_id, status);

create index checklist_runs_company_id_idx on public.checklist_runs (company_id);

create index checklist_runs_service_area_status_idx
    on public.checklist_runs (service_area_code, status);

create index checklist_run_items_run_sort_idx
    on public.checklist_run_items (checklist_run_id, sort_index);

create index saved_text_snippets_area_kind_active_idx
    on public.saved_text_snippets (service_area_code, kind, is_active);

create index audit_events_entity_created_idx
    on public.audit_events (entity_type, entity_id, created_at desc);

create index audit_events_company_created_idx
    on public.audit_events (company_id, created_at desc);

create index audit_events_deal_created_idx
    on public.audit_events (deal_id, created_at desc);

create index audit_events_checklist_run_created_idx
    on public.audit_events (checklist_run_id, created_at desc);

create index audit_events_actor_sales_created_idx
    on public.audit_events (actor_sales_id, created_at desc);

create index audit_events_event_type_created_idx
    on public.audit_events (event_type, created_at desc);

create index audit_events_contact_created_idx
    on public.audit_events (contact_id, created_at desc);

create index audit_events_task_created_idx
    on public.audit_events (task_id, created_at desc)
    where task_id is not null;

alter table public.audit_events
    add constraint audit_events_source_check
        check (source in ('user', 'system', 'edge_function', 'migration', 'demo'));

alter table public.audit_events
    add constraint audit_events_retention_class_check
        check (retention_class in (
            'crm_change', 'security', 'user_management', 'checklist', 'integration', 'system'
        ));

-- v0.4c.1 Google Calendar read-only (see migration 20260716120000)
create table public.google_calendar_connections (
    id uuid primary key default gen_random_uuid(),
    calendar_id text not null,
    calendar_name text,
    google_account_email text,
    status text not null default 'disconnected',
    scopes_granted text[] not null default '{}'::text[],
    connected_by uuid,
    connected_at timestamptz,
    disconnected_at timestamptz,
    last_sync_at timestamptz,
    last_sync_error text,
    sync_token text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint google_calendar_connections_status_check
        check (status in ('disconnected', 'connecting', 'connected', 'error', 'token_expired')),
    constraint google_calendar_connections_calendar_id_nonempty
        check (length(trim(calendar_id)) > 0)
);

create unique index google_calendar_connections_one_connected_idx
    on public.google_calendar_connections (status)
    where status = 'connected';

create table public.google_calendar_events (
    id uuid primary key default gen_random_uuid(),
    connection_id uuid not null references public.google_calendar_connections (id) on delete restrict,
    google_event_id text not null,
    google_ical_uid text,
    google_etag text,
    origin text not null default 'google',
    google_status text,
    title_snapshot text,
    description_snapshot text,
    location_snapshot text,
    html_link text,
    is_all_day boolean not null default false,
    starts_at timestamptz,
    ends_at timestamptz,
    start_date date,
    end_date date,
    timezone text,
    recurring_event_id text,
    original_start_at timestamptz,
    google_updated_at timestamptz,
    company_id bigint references public.companies (id) on delete set null,
    contact_id bigint references public.contacts (id) on delete set null,
    deal_id bigint references public.deals (id) on delete set null,
    last_synced_at timestamptz,
    deleted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint google_calendar_events_origin_check
        check (origin in ('google', 'nora')),
    constraint google_calendar_events_google_event_id_nonempty
        check (length(trim(google_event_id)) > 0),
    constraint google_calendar_events_description_snapshot_len
        check (description_snapshot is null or length(description_snapshot) <= 2000),
    constraint google_calendar_events_timing_check check (
        (
            is_all_day = true
            and starts_at is null
            and ends_at is null
            and start_date is not null
            and end_date is not null
        )
        or (
            is_all_day = false
            and starts_at is not null
            and ends_at is not null
            and start_date is null
            and end_date is null
        )
    ),
    constraint google_calendar_events_unique_per_connection
        unique (connection_id, google_event_id)
);

create table nora_private.google_calendar_oauth_secrets (
    connection_id uuid primary key references public.google_calendar_connections (id) on delete cascade,
    refresh_token_ciphertext text not null,
    encryption_key_id text not null default 'v1',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table nora_private.google_oauth_states (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null,
    state_hash text not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);
